export const ruContent = {
  metadata: {
    title: "CarPool | Совместные поездки по Бишкеку",
    description:
      "MVP сервиса совместных поездок для ежедневных маршрутов по Бишкеку.",
  },
  nav: {
    brand: "CarPool",
    trips: "Поездки",
    myTrips: "Мои поездки",
    myBookings: "Мои брони",
    notifications: "Уведомления",
    dashboard: "Кабинет",
    signIn: "Войти",
    signOut: "Выйти",
    signOutPending: "Выходим...",
    menu: "Меню",
  },
  auth: {
    signIn: {
      eyebrow: "Вход в сервис",
      title: "Войди, чтобы настроить профиль и начать проверять первые маршруты.",
      description:
        "Пока для MVP-разработки вход упрощен: достаточно email, а имя можно указать сразу или заполнить на следующем шаге.",
      emailLabel: "Email",
      emailPlaceholder: "eldiyar@example.com",
      nameLabel: "Имя",
      namePlaceholder: "Как к тебе обращаться",
      nameHint: "Имя можно пропустить и заполнить на следующем шаге onboarding.",
      submit: "Продолжить",
      pending: "Входим...",
      error: "Не удалось выполнить вход. Проверь email и попробуй еще раз.",
      homeLink: "На главную",
    },
  },
  onboarding: {
    eyebrow: "Профиль пользователя",
    title: "Заполни базовый профиль, чтобы продолжить работу с поездками.",
    description:
      "Для MVP пока нужны только имя, телефон и Telegram username. Этого достаточно для связи и базового trust layer.",
    nameLabel: "Имя",
    phoneLabel: "Телефон",
    telegramLabel: "Telegram username",
    namePlaceholder: "Элдияр",
    phonePlaceholder: "+996555123456",
    telegramPlaceholder: "rowdykg",
    helper: "Telegram username указывай без символа @.",
    submit: "Сохранить профиль",
    pending: "Сохраняем профиль...",
    genericError: "Проверь поля формы и попробуй снова.",
    uniquePhoneError: "Этот номер уже привязан к другому аккаунту.",
    uniqueTelegramError: "Этот Telegram username уже используется.",
  },
  driverOnboarding: {
    eyebrow: "Профиль водителя",
    title: "Добавь профиль водителя и машину, чтобы перейти к созданию первой поездки.",
    description:
      "Для MVP водитель сам задает машину и базовую информацию о себе. Пока считаем одну активную машину на аккаунт, чтобы быстрее проверить спрос.",
    bioLabel: "Коротко о водителе",
    bioPlaceholder: "Например: езжу по будням утром и вечером, без курения в салоне.",
    bioHelper: "Поле необязательное, но помогает повысить доверие перед первой бронью.",
    makeLabel: "Марка",
    makePlaceholder: "Toyota",
    modelLabel: "Модель",
    modelPlaceholder: "Camry",
    colorLabel: "Цвет",
    colorPlaceholder: "Белый",
    plateLabel: "Госномер",
    platePlaceholder: "01KG123ABC",
    plateHelper: "Номер нужен для доверия и ручной модерации. Можно указывать без пробелов.",
    seatsLabel: "Количество мест",
    seatsPlaceholder: "4",
    seatsHelper: "Это общая вместимость машины для будущих поездок в MVP.",
    submit: "Сохранить профиль водителя",
    updateSubmit: "Сохранить изменения",
    pending: "Сохраняем профиль водителя...",
    genericError: "Проверь данные водителя и машины и попробуй еще раз.",
    uniquePlateError: "Этот госномер уже используется в другом аккаунте.",
    pendingNote: "После этого шага можно переходить к созданию поездки.",
    completedNote: "Профиль водителя уже сохранен. Здесь можно обновить данные машины.",
  },
  dashboard: {
    eyebrow: "Личный кабинет",
    title: "Профиль готов. Следующий шаг - машина и первая поездка.",
    readyTitle: "Профиль водителя готов. Опубликуй первую поездку.",
    description:
      "Auth и базовый onboarding уже подключены. Теперь можно идти к профилю водителя, машине и созданию поездки.",
    readyDescription:
      "Базовый профиль, профиль водителя и машина уже сохранены. Создай поездку по маршруту — пассажиры смогут её найти и забронировать место.",
    browseTrips: "Найти поездку",
    createTrip: "Создать поездку",
    myBookings: "Мои брони",
    myTrips: "Мои поездки",
    editProfile: "Редактировать профиль",
    setupDriver: "Настроить профиль водителя",
    manageDriver: "Редактировать машину",
    signOut: "Выйти",
    signOutPending: "Выходим...",
    cards: {
      name: "Имя",
      email: "Email",
      phone: "Телефон",
      telegram: "Telegram",
      status: "Статус",
      completed: "Профиль заполнен",
      driverStatus: "Статус водителя",
      driverCompleted: "Машина настроена",
      driverPending: "Нужно добавить машину",
      vehicle: "Машина",
    },
  },
  tripNew: {
    eyebrow: "Новая поездка",
    title: "Опубликуй поездку по маршруту.",
    description:
      "Укажи детали — пассажиры увидят поездку в общем списке и смогут забронировать место.",
    fromDistrictLabel: "Откуда (район)",
    toDistrictLabel: "Куда (район)",
    selectPlaceholder: "Выбери район",
    pickupLabelField: "Точка посадки",
    pickupPlaceholder: "Адрес или ориентир, где заберёшь пассажиров",
    dropoffLabelField: "Точка высадки",
    dropoffPlaceholder: "Адрес или ориентир конечной точки",
    departureLabel: "Дата и время выезда",
    priceLabel: "Цена за место, сом",
    pricePlaceholder: "100",
    seatsLabel: "Количество мест",
    seatsHelper: "Вместимость машины:",
    commentLabel: "Комментарий",
    commentPlaceholder: "Необязательно: особенности посадки, предпочтения в салоне...",
    submit: "Опубликовать поездку",
    pending: "Публикуем...",
    genericError: "Проверь данные поездки и попробуй снова.",
    pastDateError: "Дата выезда должна быть в будущем.",
    invalidDateError: "Некорректная дата выезда.",
  },
  tripMap: {
    heading: "Точки на карте",
    helper:
      "Выбери активную точку и нажми на карту, чтобы поставить метку. Маркеры можно перетаскивать — адрес подставится автоматически.",
    pickupMode: "Точка посадки (A)",
    dropoffMode: "Точка высадки (Б)",
    pickupMarker: "Посадка",
    dropoffMarker: "Высадка",
    geocoding: "Определяем адрес…",
    routing: "Строим маршрут…",
    geocodeError: "Не удалось определить адрес — впиши его вручную.",
    routePreview: "Маршрут на карте",
  },
  trip: {
    eyebrow: "Поездка",
    from: "Откуда",
    to: "Куда",
    pickup: "Точка посадки",
    dropoff: "Точка высадки",
    departure: "Дата и время выезда",
    price: "Цена за место",
    seats: "Мест свободно",
    driver: "Водитель",
    vehicle: "Машина",
    comment: "Комментарий",
    statusPublished: "Принимает брони",
    statusCancelled: "Отменена",
    statusCompleted: "Завершена",
    currency: "сом",
    backToDashboard: "В кабинет",
  },
  driverBookings: {
    sectionTitle: "Заявки на бронирование",
    empty: "Заявок пока нет.",
    seatsUnit: "мест",
    statusPending: "Ожидает",
    statusConfirmed: "Подтверждена",
    statusRejected: "Отклонена",
    statusCancelled: "Отменена",
    statusCompleted: "Завершена",
    statusNoShow: "Не явился",
    confirm: "Подтвердить",
    confirmPending: "Подтверждаем...",
    reject: "Отклонить",
    rejectPending: "Отклоняем...",
  },
  driverTrip: {
    sectionTitle: "Управление поездкой",
    complete: "Завершить поездку",
    completePending: "Завершаем...",
    completeConfirm:
      "Отметить поездку завершённой? Подтверждённые брони станут завершёнными.",
    cancel: "Отменить поездку",
    cancelPending: "Отменяем...",
    cancelConfirm:
      "Отменить поездку? Все активные брони будут отменены, пассажиры потеряют места.",
    error: "Не удалось выполнить действие. Попробуй снова.",
  },
  review: {
    driverSectionTitle: "Оцените пассажиров",
    passengerSectionTitle: "Оцените водителя",
    ratingLabel: "Оценка",
    commentLabel: "Комментарий",
    commentPlaceholder: "Как прошла поездка?",
    submit: "Оставить отзыв",
    pending: "Отправляем...",
    done: "Отзыв оставлен",
    yourRating: "Ваша оценка",
    ratingUnit: "из 5",
    noPassengers: "Завершённых пассажиров нет.",
    notParticipant: "Оставить отзыв можно только участнику завершённой поездки.",
    alreadyReviewed: "Ты уже оставил отзыв этому участнику.",
    error: "Не удалось сохранить отзыв. Попробуй снова.",
  },
  notifications: {
    eyebrow: "Уведомления",
    title: "Твои уведомления",
    description: "События по твоим поездкам и броням.",
    empty: "Уведомлений пока нет.",
    markRead: "Отметить прочитанными",
    markReadPending: "Отмечаем...",
    bookingRequest: (p: { passengerName: string; route: string; seats: number }) => ({
      title: "Новая заявка на бронь",
      body: `${p.passengerName} хочет забронировать ${p.seats} мест на поездку ${p.route}.`,
    }),
    bookingConfirmed: (p: { route: string }) => ({
      title: "Бронь подтверждена",
      body: `Водитель подтвердил твою бронь на поездку ${p.route}. Контакты доступны на странице поездки.`,
    }),
    bookingRejected: (p: { route: string }) => ({
      title: "Бронь отклонена",
      body: `Водитель отклонил твою бронь на поездку ${p.route}.`,
    }),
    bookingCancelled: (p: { passengerName: string; route: string }) => ({
      title: "Пассажир отменил бронь",
      body: `${p.passengerName} отменил бронь на поездку ${p.route}. Места снова свободны.`,
    }),
    tripCancelled: (p: { route: string }) => ({
      title: "Поездка отменена",
      body: `Водитель отменил поездку ${p.route}. Твоя бронь отменена.`,
    }),
  },
  myBookings: {
    eyebrow: "Мои брони",
    title: "Твои брони",
    description: "История твоих заявок на поездки.",
    empty: "У тебя пока нет броней.",
    sectionActive: "Активные",
    sectionPast: "Прошедшие",
    currency: "сом",
    openTrip: "Открыть поездку",
    contactDriver: "Контакт водителя",
    cancelCta: "Отменить бронь",
    cancelPending: "Отменяем...",
    cancelConfirm: "Отменить бронь на эту поездку?",
    cancelError: "Не удалось отменить бронь. Попробуй снова.",
  },
  myTrips: {
    eyebrow: "Мои поездки",
    title: "Твои поездки",
    description: "Поездки, которые ты опубликовал как водитель.",
    empty: "У тебя пока нет поездок.",
    createFirst: "Создать поездку",
    filterUpcoming: "Предстоящие",
    filterPast: "Прошедшие",
    pendingBookings: "заявок ожидает",
    seatsAvailable: "мест свободно",
    currency: "сом",
    openTrip: "Открыть",
    statusPublished: "Принимает брони",
    statusCancelled: "Отменена",
    statusCompleted: "Завершена",
  },
  booking: {
    sectionTitle: "Бронирование",
    seatsLabel: "Количество мест",
    seatsUnit: "мест",
    noteLabel: "Заметка для водителя",
    notePlaceholder: "Необязательно: откуда тебя подобрать, пожелания в дороге...",
    submit: "Забронировать",
    pending: "Бронируем...",
    loginCta: "Войди, чтобы забронировать",
    noSeats: "Свободных мест нет",
    tripNotAvailable: "Поездка недоступна для бронирования",
    statusPending: "Бронь на рассмотрении у водителя",
    statusConfirmed: "Бронь подтверждена",
    statusRejected: "Водитель отклонил бронь",
    statusCancelled: "Бронь отменена",
    statusCompleted: "Поездка завершена",
    statusNoShow: "Пассажир не явился",
  },
  tripsList: {
    eyebrow: "Поездки",
    title: "Доступные поездки",
    description: "Найди поездку и забронируй место.",
    filterToday: "Сегодня",
    filterTomorrow: "Завтра",
    filterAll: "Все предстоящие",
    empty: "По выбранному фильтру поездок пока нет.",
    seats: "Мест свободно",
    currency: "сом",
    openTrip: "Открыть",
    createTripCta: "Создать поездку",
  },
  common: {
    authRequired: "Сначала войди в аккаунт.",
  },
} as const;