export const ruContent = {
  metadata: {
    title: "CarPool | Совместные поездки по Бишкеку",
    description:
      "MVP сервиса совместных поездок для ежедневных маршрутов по Бишкеку.",
  },
  nav: {
    brand: "CarPool",
    trips: "Поездки",
    myTrips: "Мои поездки",
    myBookings: "Мои брони",
    notifications: "Уведомления",
    dashboard: "Кабинет",
    admin: "Админка",
    signIn: "Войти",
    signOut: "Выйти",
    signOutPending: "Выходим...",
    menu: "Меню",
  },
  auth: {
    signIn: {
      eyebrow: "Вход в сервис",
      title: "Войди, чтобы настроить профиль и начать проверять первые маршруты.",
      description:
        "Пока для MVP-разработки вход упрощен: достаточно email, а имя можно указать сразу или заполнить на следующем шаге.",
      emailLabel: "Email",
      emailPlaceholder: "eldiyar@example.com",
      nameLabel: "Имя",
      namePlaceholder: "Как к тебе обращаться",
      nameHint: "Имя можно пропустить и заполнить на следующем шаге onboarding.",
      submit: "Продолжить",
      pending: "Входим...",
      error: "Не удалось выполнить вход. Проверь email и попробуй еще раз.",
      homeLink: "На главную",
      googleCta: "Войти через Google",
      devLoginTitle: "Тестовый вход (dev)",
      noProviders: "Вход временно недоступен: не настроен ни один способ.",
    },
    telegram: {
      cta: "Войти через Telegram",
      title: "Вход через Telegram",
      step1: "Нажми кнопку — откроется наш бот в Telegram.",
      step2: "Бот пришлёт 6-значный код. Вернись сюда и введи его.",
      openBot: "Открыть бота в Telegram",
      codeLabel: "Код из Telegram",
      codePlaceholder: "______",
      verify: "Подтвердить и войти",
      pending: "Проверяем код...",
      starting: "Готовим вход...",
      reopen: "Открыть бота заново",
      unavailable: "Вход через Telegram временно недоступен.",
      errors: {
        start: "Не удалось начать вход через Telegram. Попробуй ещё раз.",
        rateLimited: "Слишком много попыток входа. Подожди немного и попробуй снова.",
        invalid: "Неверный код. Проверь и попробуй снова.",
        expired: "Срок действия кода истёк. Запроси новый.",
        not_sent: "Сначала открой бота в Telegram, чтобы получить код.",
        too_many: "Слишком много попыток. Запроси новый код.",
        blocked: "Аккаунт заблокирован. Обратись в поддержку.",
        generic: "Не удалось войти. Попробуй ещё раз.",
      },
    },
  },
  telegramBot: {
    loginCode: (code: string) =>
      `Ваш код для входа в CarPool: ${code}\n\nКод действует 10 минут. Никому его не сообщайте.`,
    loginInvalid:
      "Ссылка для входа недействительна или истекла. Запроси новую на сайте.",
    loginRateLimited:
      "Слишком много запросов кода. Подожди немного и попробуй снова.",
  },
  onboarding: {
    eyebrow: "Профиль пользователя",
    title: "Заполни базовый профиль, чтобы продолжить работу с поездками.",
    description:
      "Для MVP пока нужны только имя, телефон и Telegram username. Этого достаточно для связи и базового trust layer.",
    nameLabel: "Имя",
    phoneLabel: "Телефон",
    telegramLabel: "Telegram username (необязательно)",
    namePlaceholder: "Элдияр",
    phonePlaceholder: "+996555123456",
    telegramPlaceholder: "rowdykg",
    helper: "Если входишь через Telegram, подставится автоматически. Без символа @.",
    submit: "Сохранить профиль",
    pending: "Сохраняем профиль...",
    genericError: "Проверь поля формы и попробуй снова.",
    uniquePhoneError:
      "Этот номер уже привязан к другому аккаунту. Похоже, ты регистрировался раньше другим способом (Google или Telegram) — выйди и войди тем же способом, чтобы попасть в свой аккаунт.",
    uniqueTelegramError: "Этот Telegram username уже используется.",
  },
  profileEdit: {
    eyebrow: "Профиль",
    title: "Изменить данные профиля",
    description: "Обнови имя, телефон или Telegram username.",
    back: "В кабинет",
    submit: "Сохранить изменения",
    pending: "Сохраняем...",
  },
  driverOnboarding: {
    eyebrow: "Профиль водителя",
    title: "Добавь профиль водителя и машину, чтобы перейти к созданию первой поездки.",
    description:
      "Для MVP водитель сам задает машину и базовую информацию о себе. Пока считаем одну активную машину на аккаунт, чтобы быстрее проверить спрос.",
    bioLabel: "Коротко о водителе",
    bioPlaceholder: "Например: езжу по будням утром и вечером, без курения в салоне.",
    bioHelper: "Поле необязательное, но помогает повысить доверие перед первой бронью.",
    makeLabel: "Марка",
    makePlaceholder: "Toyota",
    modelLabel: "Модель",
    modelPlaceholder: "Camry",
    colorLabel: "Цвет",
    colorPlaceholder: "Белый",
    plateLabel: "Госномер",
    platePlaceholder: "01KG123ABC",
    plateHelper: "Номер нужен для доверия и ручной модерации. Можно указывать без пробелов.",
    seatsLabel: "Количество мест",
    seatsPlaceholder: "4",
    seatsHelper: "Это общая вместимость машины для будущих поездок в MVP.",
    submit: "Сохранить профиль водителя",
    updateSubmit: "Сохранить изменения",
    pending: "Сохраняем профиль водителя...",
    genericError: "Проверь данные водителя и машины и попробуй еще раз.",
    uniquePlateError: "Этот госномер уже используется в другом аккаунте.",
    pendingNote: "После этого шага можно переходить к созданию поездки.",
    completedNote: "Профиль водителя уже сохранен. Здесь можно обновить данные машины.",
  },
  dashboard: {
    eyebrow: "Личный кабинет",
    title: "Профиль готов. Следующий шаг - машина и первая поездка.",
    readyTitle: "Профиль водителя готов. Опубликуй первую поездку.",
    description:
      "Auth и базовый onboarding уже подключены. Теперь можно идти к профилю водителя, машине и созданию поездки.",
    readyDescription:
      "Базовый профиль, профиль водителя и машина уже сохранены. Создай поездку по маршруту — пассажиры смогут её найти и забронировать место.",
    browseTrips: "Найти поездку",
    createTrip: "Создать поездку",
    myBookings: "Мои брони",
    myTrips: "Мои поездки",
    editProfile: "Редактировать профиль",
    setupDriver: "Настроить профиль водителя",
    manageDriver: "Редактировать машину",
    connectTelegram: "Подключить Telegram",
    reconnectTelegram: "Переподключить Telegram",
    signOut: "Выйти",
    signOutPending: "Выходим...",
    cards: {
      name: "Имя",
      email: "Email",
      phone: "Телефон",
      telegram: "Telegram",
      status: "Статус",
      completed: "Профиль заполнен",
      driverStatus: "Статус водителя",
      driverCompleted: "Машина настроена",
      driverPending: "Нужно добавить машину",
      vehicle: "Машина",
      telegramNotifications: "Telegram-уведомления",
      telegramConnected: "Подключены",
      telegramDisconnected: "Не подключены",
    },
  },
  tripNew: {
    eyebrow: "Новая поездка",
    title: "Опубликуй поездку по маршруту.",
    description:
      "Укажи детали — пассажиры увидят поездку в общем списке и смогут забронировать место.",
    fromDistrictLabel: "Откуда (район)",
    toDistrictLabel: "Куда (район)",
    selectPlaceholder: "Выбери район",
    pickupLabelField: "Точка посадки",
    pickupPlaceholder: "Адрес или ориентир, где заберёшь пассажиров",
    dropoffLabelField: "Точка высадки",
    dropoffPlaceholder: "Адрес или ориентир конечной точки",
    departureLabel: "Дата и время выезда",
    priceLabel: "Цена за место, сом",
    pricePlaceholder: "100",
    seatsLabel: "Количество мест",
    seatsHelper: "Вместимость машины:",
    commentLabel: "Комментарий",
    commentPlaceholder: "Необязательно: особенности посадки, предпочтения в салоне...",
    submit: "Опубликовать поездку",
    pending: "Публикуем...",
    genericError: "Проверь данные поездки и попробуй снова.",
    pastDateError: "Дата выезда должна быть в будущем.",
    invalidDateError: "Некорректная дата выезда.",
  },
  tripEdit: {
    eyebrow: "Редактирование поездки",
    title: "Измени детали поездки.",
    submit: "Сохранить изменения",
    pending: "Сохраняем...",
    seatsBelowBookedError:
      "Нельзя сделать мест меньше, чем уже забронировано.",
    notEditableError: "Эту поездку нельзя отредактировать.",
  },
  tripMap: {
    heading: "Точки на карте",
    helper:
      "Выбери активную точку и нажми на карту, чтобы поставить метку. Маркеры можно перетаскивать — адрес подставится автоматически.",
    pickupMode: "Точка посадки (A)",
    dropoffMode: "Точка высадки (Б)",
    pickupMarker: "Посадка",
    dropoffMarker: "Высадка",
    geocoding: "Определяем адрес…",
    routing: "Строим маршрут…",
    geocodeError: "Не удалось определить адрес — впиши его вручную.",
    routePreview: "Маршрут на карте",
  },
  trip: {
    eyebrow: "Поездка",
    from: "Откуда",
    to: "Куда",
    pickup: "Точка посадки",
    dropoff: "Точка высадки",
    departure: "Дата и время выезда",
    price: "Цена за место",
    seats: "Мест свободно",
    driver: "Водитель",
    vehicle: "Машина",
    comment: "Комментарий",
    statusPublished: "Принимает брони",
    statusCancelled: "Отменена",
    statusCompleted: "Завершена",
    currency: "сом",
    backToDashboard: "В кабинет",
    saveAsTemplate: "Сохранить как шаблон",
    repeat: "Повторить поездку",
    edit: "Изменить",
    ownerActionsTitle: "Действия с маршрутом",
  },
  driverBookings: {
    sectionTitle: "Заявки на бронирование",
    empty: "Заявок пока нет.",
    seatsUnit: "мест",
    statusPending: "Ожидает",
    statusConfirmed: "Подтверждена",
    statusRejected: "Отклонена",
    statusCancelled: "Отменена",
    statusCompleted: "Завершена",
    statusNoShow: "Не явился",
    confirm: "Подтвердить",
    confirmPending: "Подтверждаем...",
    reject: "Отклонить",
    rejectPending: "Отклоняем...",
    markNoShow: "Не приехал",
    markNoShowPending: "Отмечаем...",
    markNoShowConfirm: "Отметить, что пассажир не приехал?",
    markAttended: "Вернуть «приехал»",
    markAttendedPending: "Возвращаем...",
  },
  driverTrip: {
    sectionTitle: "Управление поездкой",
    complete: "Завершить поездку",
    completePending: "Завершаем...",
    completeConfirm:
      "Отметить поездку завершённой? Подтверждённые брони станут завершёнными.",
    cancel: "Отменить поездку",
    cancelPending: "Отменяем...",
    cancelConfirm:
      "Отменить поездку? Все активные брони будут отменены, пассажиры потеряют места.",
    error: "Не удалось выполнить действие. Попробуй снова.",
  },
  review: {
    driverSectionTitle: "Оцените пассажиров",
    passengerSectionTitle: "Оцените водителя",
    ratingLabel: "Оценка",
    commentLabel: "Комментарий",
    commentPlaceholder: "Как прошла поездка?",
    submit: "Оставить отзыв",
    pending: "Отправляем...",
    done: "Отзыв оставлен",
    yourRating: "Ваша оценка",
    ratingUnit: "из 5",
    noPassengers: "Завершённых пассажиров нет.",
    notParticipant: "Оставить отзыв можно только участнику завершённой поездки.",
    alreadyReviewed: "Ты уже оставил отзыв этому участнику.",
    error: "Не удалось сохранить отзыв. Попробуй снова.",
  },
  admin: {
    title: "Админка",
    navOverview: "Обзор",
    navUsers: "Пользователи",
    navTrips: "Поездки",
    navReports: "Жалобы",
    overviewUsers: "Пользователи",
    overviewTrips: "Активные поездки",
    overviewReports: "Открытые жалобы",
    usersTitle: "Пользователи",
    tripsTitle: "Поездки",
    reportsTitle: "Жалобы",
    block: "Заблокировать",
    suspend: "Ограничить",
    activate: "Разблокировать",
    hideTrip: "Скрыть",
    resolve: "Решена",
    dismiss: "Отклонить",
    empty: "Пусто.",
    openTrip: "Поездка",
    reportedTrip: "Поездка в жалобе",
    roleAdmin: "Админ",
    statusActive: "Активен",
    statusSuspended: "Ограничен",
    statusBlocked: "Заблокирован",
    reportOpen: "Открыта",
    reportReviewed: "На проверке",
    reportResolved: "Решена",
    reportDismissed: "Отклонена",
  },
  report: {
    cta: "Пожаловаться на поездку",
    reasonLabel: "Причина жалобы",
    reasonPlaceholder: "Опиши, что не так с поездкой или водителем",
    submit: "Отправить жалобу",
    pending: "Отправляем...",
    done: "Жалоба отправлена. Спасибо, мы проверим.",
    error: "Не удалось отправить жалобу. Попробуй снова.",
  },
  notifications: {
    eyebrow: "Уведомления",
    title: "Твои уведомления",
    description: "События по твоим поездкам и броням.",
    empty: "Уведомлений пока нет.",
    markRead: "Отметить прочитанными",
    markReadPending: "Отмечаем...",
    bookingRequest: (p: { passengerName: string; route: string; seats: number }) => ({
      title: "Новая заявка на бронь",
      body: `${p.passengerName} хочет забронировать ${p.seats} мест на поездку ${p.route}.`,
    }),
    bookingConfirmed: (p: { route: string }) => ({
      title: "Бронь подтверждена",
      body: `Водитель подтвердил твою бронь на поездку ${p.route}. Контакты доступны на странице поездки.`,
    }),
    bookingRejected: (p: { route: string }) => ({
      title: "Бронь отклонена",
      body: `Водитель отклонил твою бронь на поездку ${p.route}.`,
    }),
    bookingCancelled: (p: { passengerName: string; route: string }) => ({
      title: "Пассажир отменил бронь",
      body: `${p.passengerName} отменил бронь на поездку ${p.route}. Места снова свободны.`,
    }),
    tripCancelled: (p: { route: string }) => ({
      title: "Поездка отменена",
      body: `Водитель отменил поездку ${p.route}. Твоя бронь отменена.`,
    }),
    tripUpdated: (p: { route: string; time: string }) => ({
      title: "Детали поездки изменились",
      body: `Водитель изменил поездку ${p.route}. Новое время выезда: ${p.time}. Проверь детали на странице поездки.`,
    }),
    tripReminder: (p: { route: string; time: string }) => ({
      title: "Скоро выезд",
      body: `Напоминание: поездка ${p.route} — выезд ${p.time}.`,
    }),
    reviewRequestPassenger: (p: { route: string }) => ({
      title: "Оцените поездку",
      body: `Поездка ${p.route} завершена. Оставьте отзыв о водителе на странице поездки.`,
    }),
    reviewRequestDriver: (p: { route: string }) => ({
      title: "Оцените пассажиров",
      body: `Поездка ${p.route} завершена. Оставьте отзыв о пассажирах на странице поездки.`,
    }),
  },
  myBookings: {
    eyebrow: "Мои брони",
    title: "Твои брони",
    description: "История твоих заявок на поездки.",
    empty: "У тебя пока нет броней.",
    sectionActive: "Активные",
    sectionPast: "Прошедшие",
    currency: "сом",
    openTrip: "Открыть поездку",
    contactDriver: "Контакт водителя",
    cancelCta: "Отменить бронь",
    cancelPending: "Отменяем...",
    cancelConfirm: "Отменить бронь на эту поездку?",
    cancelError: "Не удалось отменить бронь. Попробуй снова.",
  },
  myTrips: {
    eyebrow: "Мои поездки",
    title: "Твои поездки",
    description: "Поездки, которые ты опубликовал как водитель.",
    empty: "У тебя пока нет поездок.",
    createFirst: "Создать поездку",
    filterUpcoming: "Предстоящие",
    filterPast: "Прошедшие",
    pendingBookings: "заявок ожидает",
    seatsAvailable: "мест свободно",
    currency: "сом",
    openTrip: "Открыть",
    statusPublished: "Принимает брони",
    statusCancelled: "Отменена",
    statusCompleted: "Завершена",
    templatesLink: "Шаблоны маршрутов",
  },
  tripTemplates: {
    eyebrow: "Шаблоны",
    title: "Шаблоны маршрутов",
    description:
      "Сохраняй частые маршруты и запускай поездку в пару кликов — не заполняя всё заново.",
    create: "Новый шаблон",
    empty: "У тебя пока нет шаблонов. Создай первый — и запускай поездки по нему каждый день.",
    launch: "Запустить",
    reverse: "Обратный",
    edit: "Изменить",
    delete: "Удалить",
    deleteConfirm: "Удалить шаблон?",
    noTime: "Время не задано",
    timePrefix: "Выезд в",
    currency: "сом",
    seats: "мест",
    untitled: "Без названия",
    back: "Мои поездки",
    fromTripTitle: "Создать из активной поездки",
    fromTripHint: "Выбери опубликованную поездку — сохраним её как шаблон.",
    fromTripPlaceholder: "Выбери поездку",
    fromTripButton: "Сохранить как шаблон",
    fromTripEmpty: "Нет активных поездок для сохранения.",
  },
  tripTemplateNew: {
    eyebrow: "Новый шаблон",
    title: "Сохрани маршрут как шаблон.",
    description:
      "Заполни маршрут один раз — потом запускай поездки по нему, указывая только дату.",
    titleLabel: "Название (необязательно)",
    titlePlaceholder: "Например: Дом → Работа",
    pickupLabelField: "Точка посадки",
    pickupPlaceholder: "Адрес или ориентир, где заберёшь пассажиров",
    dropoffLabelField: "Точка высадки",
    dropoffPlaceholder: "Адрес или ориентир конечной точки",
    timeLabel: "Время выезда (необязательно)",
    timeHelper: "Подставится при запуске; дату выберешь при создании поездки.",
    priceLabel: "Цена за место, сом",
    pricePlaceholder: "100",
    seatsLabel: "Количество мест",
    seatsHelper: "Вместимость машины:",
    commentLabel: "Комментарий",
    commentPlaceholder: "Необязательно: особенности посадки, предпочтения в салоне...",
    submit: "Сохранить шаблон",
    pending: "Сохраняем...",
    genericError: "Проверь данные шаблона и попробуй снова.",
    duplicateError:
      "Похожий шаблон уже есть — с тем же маршрутом и временем. Открой список шаблонов.",
  },
  tripTemplateEdit: {
    eyebrow: "Редактирование шаблона",
    title: "Измени шаблон маршрута.",
  },
  booking: {
    sectionTitle: "Бронирование",
    seatsLabel: "Количество мест",
    seatsUnit: "мест",
    noteLabel: "Заметка для водителя",
    notePlaceholder: "Необязательно: откуда тебя подобрать, пожелания в дороге...",
    submit: "Забронировать",
    pending: "Бронируем...",
    loginCta: "Войди, чтобы забронировать",
    noSeats: "Свободных мест нет",
    tripNotAvailable: "Поездка недоступна для бронирования",
    statusPending: "Бронь на рассмотрении у водителя",
    statusConfirmed: "Бронь подтверждена",
    statusRejected: "Водитель отклонил бронь",
    statusCancelled: "Бронь отменена",
    statusCompleted: "Поездка завершена",
    statusNoShow: "Пассажир не явился",
  },
  tripsList: {
    eyebrow: "Поездки",
    title: "Доступные поездки",
    description: "Найди поездку и забронируй место.",
    filterToday: "Сегодня",
    filterTomorrow: "Завтра",
    filterAll: "Все предстоящие",
    filterFrom: "Откуда (район)",
    filterTo: "Куда (район)",
    filterAnyDistrict: "Любой район",
    empty: "По выбранному фильтру поездок пока нет.",
    seats: "Мест свободно",
    currency: "сом",
    openTrip: "Открыть",
    createTripCta: "Создать поездку",
    prevPage: "Назад",
    nextPage: "Дальше",
  },
  common: {
    authRequired: "Сначала войди в аккаунт.",
    loading: "Загрузка...",
  },
  pagination: {
    prev: "Назад",
    next: "Дальше",
  },
  errorPages: {
    notFoundTitle: "Страница не найдена",
    notFoundDescription:
      "Похоже, такой страницы нет или она была удалена. Проверь ссылку или вернись на главную.",
    home: "На главную",
    errorTitle: "Что-то пошло не так",
    errorDescription:
      "Произошла ошибка. Попробуй обновить страницу — если не поможет, вернись позже.",
    retry: "Попробовать снова",
  },
} as const;